"""added statatus column to games table

Revision ID: 2827387f234e
Revises: 698b5f901786
Create Date: 2026-08-04 15:41:48.587072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2827387f234e'
down_revision = '698b5f901786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), server_default='Pre-Game', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
