"""empty message

Revision ID: 698b5f901786
Revises: a92910d169da
Create Date: 2026-08-03 12:30:06.694016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '698b5f901786'
down_revision = 'a92910d169da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('settings', sa.JSON(), nullable=True))
        batch_op.drop_column('rounds')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rounds', sqlite.JSON(), nullable=True))
        batch_op.drop_column('settings')

    # ### end Alembic commands ###
