"""created games table

Revision ID: 6d155d495624
Revises: 
Create Date: 2026-08-02 17:48:34.825020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d155d495624'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('host_name', sa.String(), nullable=True),
    sa.Column('players', sa.JSON(), nullable=True),
    sa.Column('words', sa.JSON(), nullable=True),
    sa.Column('teams', sa.JSON(), nullable=True),
    sa.Column('rounds', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###
